services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $queryBus: '@query.bus'
            $commandBus: '@command.bus'

    Tests\Behat\:
        resource: '../tests/Behat/*'